sonar.organization=widyaadepivot
sonar.projectKey=widyaadepivot_go-sonar-quality-gate

sonar.sources=.
sonar.exclusions=**/vendor/**,.github/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.activate=true
sonar.go.file.suffixes=.go
sonar.go.exclusions=**/vendor/**,**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.go.golangci-lint.reportPaths=golangci-lint.xml

sonar.coverage.exclusions=**/vendor/**

#sonar.qualitygate.wait=true
#sonar.qualitygate.timeout=600
