on:
  push:
    branches:
      - main

name: Sonarqube Quality Gate
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Download and verify dependencies
      run: go mod download -x && go mod verify

    - name: Run unit tests
      run: go test -race -covermode=atomic -coverprofile=coverage.out

    - name: Run static analyze (golangci-lint)
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.11
        args: --issues-exit-code=0 --output.checkstyle.path=./golangci-lint.xml

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
